#!/usr/bin/env bash

## Start and watch project with browsersync.
## This does not currently work with Docksal!
##
## Usage: fin npm-build

PWD=$(pwd)
cd ${PROJECT_ROOT}/${SRCROOT}
npm run start
cd ${PWD}
